version: "3.1"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database:db

  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: currency
    volumes:
      - ./mysql:/var/lib/mysql
